"use client";

import { useState, useEffect } from "react";
import { CheckSquare, ShieldAlert, CheckCircle2, XCircle, AlertTriangle, ArrowRight } from "lucide-react";

export default function ApprovalCenterPage() {
  const [requests, setRequests] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [processingId, setProcessingId] = useState<string | null>(null);

  useEffect(() => {
    fetchRequests();
  }, []);

  async function fetchRequests() {
    try {
      const res = await fetch("/api/approval");
      if (res.ok) {
        const json = await res.json();
        setRequests(json.data || []);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  async function handleAction(id: string, action: "approved" | "rejected") {
    setProcessingId(id);
    try {
      const res = await fetch("/api/approval", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, action }),
      });

      if (res.ok) {
        await fetchRequests();
      }
    } catch (err) {
      console.error(err);
    } finally {
      setProcessingId(null);
    }
  }

  const pending = requests.filter((r) => r.status === "pending");
  const reviewed = requests.filter((r) => r.status !== "pending");

  return (
    <div style={{ padding: "32px 40px", maxWidth: 1400, margin: "0 auto", color: "var(--text)" }}>
      <div style={{ marginBottom: 32 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 6 }}>
          <ShieldAlert size={28} style={{ color: "#f87171" }} />
          <h1 style={{ fontSize: 28, fontWeight: 800, fontFamily: "var(--font-display)", margin: 0 }}>
            Approval Center (Human-in-the-Loop)
          </h1>
        </div>
        <p style={{ color: "var(--muted)", fontSize: 14, margin: 0 }}>
          Human gate review queue for high-risk budget increases and campaign actions generated by RocketRide.
        </p>
      </div>

      {/* Pending Approvals */}
      <div style={{ marginBottom: 40 }}>
        <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 20 }}>
          Pending Actions Requiring Approval ({pending.length})
        </h2>

        {pending.length === 0 ? (
          <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: 32, textAlign: "center", color: "var(--muted)" }}>
            🎉 No pending approval requests in queue. All high-risk campaign actions are reviewed!
          </div>
        ) : (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {pending.map((req) => (
              <div key={req.id} style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: 24 }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                    <span style={{ background: "rgba(248,113,113,0.15)", color: "#f87171", border: "1px solid rgba(248,113,113,0.3)", padding: "3px 10px", borderRadius: 12, fontSize: 11, fontWeight: 700 }}>
                      HIGH RISK ACTION
                    </span>
                    <span style={{ fontSize: 12, color: "var(--muted)", fontFamily: "var(--font-mono)" }}>
                      ACTION: {req.action_type?.toUpperCase()}
                    </span>
                  </div>
                  <span style={{ fontSize: 12, color: "#a78bfa", fontWeight: 700 }}>
                    Confidence Score: {(req.confidence_score * 100).toFixed(0)}%
                  </span>
                </div>

                <h3 style={{ fontSize: 16, fontWeight: 700, margin: "0 0 8px 0" }}>
                  {req.proposed_change?.campaign_name || "Q3 Growth Scale — Founder UGC Hooks"}
                </h3>

                <p style={{ fontSize: 13, color: "var(--muted)", margin: "0 0 16px 0", lineHeight: 1.5 }}>
                  {req.reasoning}
                </p>

                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", background: "var(--background)", border: "1px solid var(--border)", borderRadius: 8, padding: 16, marginBottom: 16 }}>
                  <div>
                    <div style={{ fontSize: 11, color: "var(--muted)" }}>CURRENT BUDGET</div>
                    <div style={{ fontSize: 16, fontWeight: 700 }}>${req.current_budget}/day</div>
                  </div>
                  <ArrowRight size={20} style={{ color: "var(--muted)" }} />
                  <div>
                    <div style={{ fontSize: 11, color: "var(--muted)" }}>PROPOSED BUDGET</div>
                    <div style={{ fontSize: 16, fontWeight: 700, color: "#34d399" }}>${req.proposed_budget}/day</div>
                  </div>
                </div>

                <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
                  <button
                    onClick={() => handleAction(req.id, "rejected")}
                    disabled={processingId === req.id}
                    style={{
                      background: "transparent", border: "1px solid rgba(248,113,113,0.3)", color: "#f87171",
                      padding: "10px 20px", borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: "pointer",
                      display: "flex", alignItems: "center", gap: 8
                    }}
                  >
                    <XCircle size={16} /> Reject Action
                  </button>
                  <button
                    onClick={() => handleAction(req.id, "approved")}
                    disabled={processingId === req.id}
                    style={{
                      background: "#34d399", color: "#000", border: "none",
                      padding: "10px 20px", borderRadius: 8, fontSize: 13, fontWeight: 700, cursor: "pointer",
                      display: "flex", alignItems: "center", gap: 8, boxShadow: "0 4px 12px rgba(52,211,153,0.3)"
                    }}
                  >
                    <CheckCircle2 size={16} /> Approve Action
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
